### ISSUE TITLE
mvn test failed

### ISSUE THREAD

**Issue by quanghoc** [cloudera/livy#14]
I have Clouder 5.5 Express and Spark 1.5 in master node where Livy installed.

My build was successfully but `mvn test` gave below error:

```
InteractiveSessionProcessSpec:
A spark session
- should start in the starting or idle state
- should eventually become the idle state
- should execute `1 + 2` == 3 *** FAILED ***
  JObject(List((status,JString(error)), (execution_count,JInt(0)), (ename,JString(Error)), (evalue,JString(Interpreter died:
  Traceback (most recent call last):
    File "/tmp/4767205653864955903", line 446, in <module>
      sys.exit(main())
    File "/tmp/4767205653864955903", line 372, in main
      exec 'from pyspark.shell import sc' in global_dict
    File "<string>", line 1, in <module>
    File "/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/python/lib/pyspark.zip/pyspark/shell.py", line 43, in <module>
```

and

```
*** 3 TESTS FAILED ***
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] livy-main .......................................... SUCCESS [  1.366 s]
[INFO] livy-api_2.10 ...................................... SUCCESS [  5.085 s]
[INFO] livy-client-local_2.10 ............................. SUCCESS [ 26.375 s]
[INFO] livy-core_2.10 ..................................... SUCCESS [  0.315 s]
[INFO] livy-repl_2.10 ..................................... SUCCESS [01:14 min]
[INFO] livy-yarn_2.10 ..................................... SUCCESS [  5.320 s]
[INFO] livy-spark_2.10 .................................... FAILURE [ 31.109 s]
[INFO] livy-server_2.10 ................................... SKIPPED
[INFO] livy-assembly_2.10 ................................. SKIPPED
[INFO] livy-client-http_2.10 .............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:24 min
[INFO] Finished at: 2015-12-21T01:30:09-05:00
[INFO] Final Memory: 42M/1199M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.scalatest:scalatest-maven-plugin:1.0:test (test) on project livy-spark_2.10: There are test failures -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :livy-spark_2.10
```

My env variables:

`export SPARK_HOME=/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark`

`export HADOOP_CONF_DIR=/etc/hadoop/conf`

Any idea on what I should fix?

**Comment by romainr** [comment]
On way to temporary skip those is to do:
mvn package -Dskip.tests=true

**Comment by quanghoc** [comment]
Well, I am doing `mvn -DskipTests clean package` anyways. So the test can fail and the `./bin/livy-server` is still just fine? If so, I guess I can ignore this then.
