### ISSUE TITLE
Error POST /statements

### ISSUE THREAD

**Issue by quanghoc** [cloudera/livy#15]
I am sending simple `{'code': '1 + 1'}` POST /statements and got error below. Any idea?

```
15/12/27 02:23:13 INFO Main$: Using spark-submit version 1.5.0-cdh5.5.0
15/12/27 02:23:13 INFO ScalatraListener: The cycle class name from the config: com.cloudera.livy.server.ScalatraBootstrap
15/12/27 02:23:13 INFO ScalatraListener: Initializing life cycle class: ScalatraBootstrap
15/12/27 02:23:14 WARN RequestLogHandler: !RequestLog
15/12/27 02:23:14 INFO WebServer: Starting server on 8998
15/12/27 02:23:28 INFO SparkProcessBuilder: Running '/opt/cloudera/parcels/CDH-5.5.0-1.cdh5.5.0.p0.8/lib/spark/bin/spark-submit' '--name' 'Livy' '--class' 'com.cloudera.livy.repl.Main' '--conf' 'spark.livy.callbackUrl=http://172.16.41.61:8998/sessions/0/callback' '--conf' 'spark.livy.port=0' '/home/zeppelin/apps/livy/livy-assembly/target/jars/livy-spark_2.10-0.2.0-SNAPSHOT.jar' 'spark'
15/12/27 02:23:28 INFO SessionManager: created session 0
15/12/27 02:24:20 ERROR SessionServlet$: internal error
java.lang.IllegalStateException: Session is in state error
	at com.cloudera.livy.spark.interactive.InteractiveWebSession.ensureRunning(InteractiveWebSession.scala:226)
	at com.cloudera.livy.spark.interactive.InteractiveWebSession.executeStatement(InteractiveWebSession.scala:80)
	at com.cloudera.livy.server.interactive.InteractiveSessionServlet$$anonfun$16.apply(InteractiveSessionServlet.scala:127)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$liftAction(ScalatraBase.scala:270)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ScalatraBase$$anonfun$invoke$1.apply(ScalatraBase.scala:265)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)
	at com.cloudera.livy.server.SessionServlet.withRouteMultiParams(SessionServlet.scala:35)
	at org.scalatra.ScalatraBase$class.invoke(ScalatraBase.scala:264)
	at com.cloudera.livy.server.SessionServlet.org$scalatra$json$JsonSupport$$super$invoke(SessionServlet.scala:35)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:74)
	at org.scalatra.json.JsonSupport$$anonfun$invoke$1.apply(JsonSupport.scala:68)
	at org.scalatra.ApiFormats$class.withRouteMultiParams(ApiFormats.scala:178)
	at com.cloudera.livy.server.SessionServlet.withRouteMultiParams(SessionServlet.scala:35)
	at org.scalatra.json.JsonSupport$class.invoke(JsonSupport.scala:68)
	at com.cloudera.livy.server.SessionServlet.invoke(SessionServlet.scala:35)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:240)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1$$anonfun$apply$8.apply(ScalatraBase.scala:238)
	at scala.Option.flatMap(Option.scala:170)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:238)
	at org.scalatra.ScalatraBase$$anonfun$runRoutes$1.apply(ScalatraBase.scala:237)
	at scala.collection.immutable.Stream.flatMap(Stream.scala:442)
	at org.scalatra.ScalatraBase$class.runRoutes(ScalatraBase.scala:237)
	at org.scalatra.ScalatraServlet.runRoutes(ScalatraServlet.scala:49)
	at org.scalatra.ScalatraBase$class.runActions$1(ScalatraBase.scala:163)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply$mcV$sp(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$$anonfun$executeRoutes$1.apply(ScalatraBase.scala:175)
	at org.scalatra.ScalatraBase$class.org$scalatra$ScalatraBase$$cradleHalt(ScalatraBase.scala:193)
	at org.scalatra.ScalatraBase$class.executeRoutes(ScalatraBase.scala:175)
	at org.scalatra.ScalatraServlet.executeRoutes(ScalatraServlet.scala:49)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply$mcV$sp(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at org.scalatra.ScalatraBase$$anonfun$handle$1.apply(ScalatraBase.scala:113)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.scalatra.DynamicScope$class.withResponse(DynamicScope.scala:80)
	at org.scalatra.ScalatraServlet.withResponse(ScalatraServlet.scala:49)
	at org.scalatra.DynamicScope$$anonfun$withRequestResponse$1.apply(DynamicScope.scala:60)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
	at org.scalatra.DynamicScope$class.withRequest(DynamicScope.scala:71)
	at org.scalatra.ScalatraServlet.withRequest(ScalatraServlet.scala:49)
	at org.scalatra.DynamicScope$class.withRequestResponse(DynamicScope.scala:59)
	at org.scalatra.ScalatraServlet.withRequestResponse(ScalatraServlet.scala:49)
	at org.scalatra.ScalatraBase$class.handle(ScalatraBase.scala:111)
	at org.scalatra.ScalatraServlet.org$scalatra$servlet$ServletBase$$super$handle(ScalatraServlet.scala:49)
	at org.scalatra.servlet.ServletBase$class.handle(ServletBase.scala:43)
	at com.cloudera.livy.server.SessionServlet.org$scalatra$MethodOverride$$super$handle(SessionServlet.scala:35)
	at org.scalatra.MethodOverride$class.handle(MethodOverride.scala:28)
	at com.cloudera.livy.server.SessionServlet.handle(SessionServlet.scala:35)
	at org.scalatra.ScalatraServlet.service(ScalatraServlet.scala:54)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:808)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:745)

```

Just for more information:

- I was able to POST /sessions and it returned `{"id":0,"state":"starting","kind":"spark","log":[]}`

- But then I believe it moved into error state when I do GET /0 (or whatever number): 

```
{"id":0,"state":"error","kind":"spark","log":["\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)","\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)","\tat java.lang.Class.forName0(Native Method)","\tat java.lang.Class.forName(Class.java:278)","\tat org.apache.spark.util.Utils$.classForName(Utils.scala:173)","\tat org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:639)","\tat org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)","\tat org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)","\tat org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)","\tat org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)"]}
```

I installed livy using `zeppelin` user with `hadoop` group for all folder and files. The `zeppelin` user can run spark-shell just fine. I have CDH 5.5 Express and Spark 1.5.

Please help.

**Comment by romainr** [comment]
Did the session at least started before sending it code?

http://gethue.com/how-to-use-the-livy-spark-rest-job-server-for-interactive-spark-2-2/

**Comment by quanghoc** [comment]
No, the session has error state like this:

```
{"id":1,"state":"error","kind":"spark","log":["\tat java.lang.ClassLoader.loadClass(ClassLoader.java:425)","\tat java.lang.ClassLoader.loadClass(ClassLoader.java:358)","\tat java.lang.Class.forName0(Native Method)","\tat java.lang.Class.forName(Class.java:278)","\tat org.apache.spark.util.Utils$.classForName(Utils.scala:173)","\tat org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:639)","\tat org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:180)","\tat org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:205)","\tat org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:120)","\tat org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)"]}
```

I don't know what causing it. Any idea?

**Comment by imarhc1** [comment]
Hi Quanghoc,

Did you solve this issue? I have the same problem as you.

Best,

imarch1

**Comment by quanghoc** [comment]
No, I just gave up and never looked back since.

**Comment by harishreedharan** [comment]
It does look like a classpath issue. It looks like there is a problem finding the livy classes. Is this file present: `/home/zeppelin/apps/livy/livy-assembly/target/jars/livy-spark_2.10-0.2.0-SNAPSHOT.jar` and readable?

@erickt Any idea of what could be going wrong here?

**Comment by ksakellis** [comment]
@quanghoc if this is still an issue, please file a Livy JIRA: https://issues.cloudera.org/browse/LIVY
